# Generated by Django 4.2 on 2023-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_change_ids_to_big_autofield_dj42'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountname',
            index=models.Index(fields=['user', 'name'], name='account_acc_user_id_880807_idx'),
        ),
        migrations.AddIndex(
            model_name='accountnameamount',
            index=models.Index(fields=['account_name', '-date'], name='account_acc_account_73c088_idx'),
        ),
        migrations.AddIndex(
            model_name='networth',
            index=models.Index(fields=['user', '-date'], name='account_net_user_id_d5f2c5_idx'),
        ),
    ]
