version: '3'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - 'expensor_db:/var/lib/postgresql/data/'

  redis:
    image: redis:bookworm
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
  
  web:
    build: .
    restart: unless-stopped
    command: sh -c "gunicorn app.main:app --config ./gunicorn.conf.py"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  celery:
    build: .
    restart: unless-stopped
    command: celery -A expensor worker -B -l info
    depends_on:
      - db
      - cache

networks:
  default:
    driver: bridge

volumes:
  expensor_db:
