# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20180330_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='remark',
            new_name='remark_old',
        ),
        migrations.AlterField(
            model_name='remark',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
