# Generated by Django 2.2.24 on 2021-08-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20210523_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-timestamp', '-created_at')},
        ),
    ]
