# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_remove_expense_remark_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='remark2',
            new_name='remark',
        ),
    ]
