# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20180330_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='remark_old',
        ),
    ]
