# Generated by Django 4.2 on 2023-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_change_ids_to_big_autofield_dj42'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='remark',
            index=models.Index(fields=['user', 'name'], name='expense_rem_user_id_d3e98b_idx'),
        ),
    ]
