# Generated by Django 4.2 on 2023-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_add_index_to_remark'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-timestamp'], name='expense_exp_user_id_9b9c10_idx'),
        ),
    ]
