# Generated by Django 2.2 on 2019-10-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20190805_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='income.Source'),
        ),
    ]
