# Generated by Django 2.2.23 on 2021-05-23 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_savingcalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='savings_min_amount',
            field=models.PositiveIntegerField(help_text='min amount that must be saved if possible. 0 to ignore'),
        ),
        migrations.AlterField(
            model_name='savingcalculation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saving_calculation', to=settings.AUTH_USER_MODEL),
        ),
    ]
