# Generated by Django 2.2.24 on 2021-06-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_auto_20210611_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingcalculation',
            name='gold_percentage',
        ),
    ]
