# Generated by Django 2.2.24 on 2021-06-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_remove_savingcalculation_gold_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='amount_to_keep_in_bank',
            field=models.PositiveIntegerField(blank=True, help_text='Should be less than monthly salary. i.e. <=90% of monthly salary', null=True),
        ),
    ]
