# Generated by Django 2.2.24 on 2021-06-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0009_auto_20210625_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='savings_max_amount',
            field=models.PositiveIntegerField(blank=True, help_text='max amount that can be saved. 0 to ignore', null=True),
        ),
        migrations.AlterField(
            model_name='savingcalculation',
            name='savings_min_amount',
            field=models.PositiveIntegerField(blank=True, help_text='min amount that must be saved if possible. 0 to ignore', null=True),
        ),
    ]
