# Generated by Django 2.2.24 on 2021-07-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0010_auto_20210627_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcalculation',
            name='message',
            field=models.TextField(blank=True, help_text='briefly explain your thought process on choosing this method', null=True),
        ),
    ]
