# Generated by Django 2.2.24 on 2021-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0011_savingcalculation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='amount_to_keep_in_bank',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Should be less than monthly salary. i.e. <=90% of monthly salary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savingcalculation',
            name='savings_max_amount',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='max amount that can be saved. 0 to ignore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savingcalculation',
            name='savings_min_amount',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='min amount that must be saved if possible. 0 to ignore'),
            preserve_default=False,
        ),
    ]
