# Generated by Django 2.2.24 on 2021-07-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0013_auto_20210708_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingcalculation',
            name='savings_max_amount',
        ),
    ]
