# Generated by Django 2.2.24 on 2021-08-13 23:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0015_auto_20210809_1452'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('user', 'name')},
        ),
    ]
