# Generated by Django 2.2.24 on 2021-08-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0016_auto_20210814_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('percentage', models.PositiveIntegerField(blank=True, default=0, help_text='in percentage')),
                ('saving_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_entity', to='income.SavingCalculation')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
