# Generated by Django 2.2.24 on 2021-08-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0017_investmententity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investmententity',
            unique_together={('saving_calculation', 'name')},
        ),
    ]
