# Generated by Django 2.2.13 on 2021-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0020_auto_20210826_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingcalculation',
            old_name='auto_fill_savings_min_amount',
            new_name='auto_fill_savings_fixed_amount',
        ),
        migrations.RenameField(
            model_name='savingcalculation',
            old_name='savings_min_amount',
            new_name='savings_fixed_amount',
        ),
    ]
