# Generated by Django 2.2.13 on 2021-11-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0021_auto_20211102_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='savings_fixed_amount',
            field=models.PositiveIntegerField(help_text='fixed amount that must be saved if possible. 0 to ignore'),
        ),
    ]
