# Generated by Django 2.2.13 on 2021-12-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0022_auto_20211102_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcalculation',
            name='amount_in_multiples_of',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='i.e. 100, 1000, etc'),
        ),
    ]
