# Generated by Django 2.2.26 on 2022-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0023_savingcalculation_amount_in_multiples_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
