# Generated by Django 2.2.28 on 2022-07-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0024_auto_20220128_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='amount_in_multiples_of',
            field=models.PositiveIntegerField(default=100, help_text='i.e. 100, 1000, etc'),
        ),
    ]
