# Generated by Django 2.2.28 on 2022-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0025_auto_20220727_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='auto_fill_amount_to_keep_in_bank',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Auto from income'), (2, '1 Month of Expense'), (3, '3 Months of Expense'), (4, '6 Months of Expense'), (5, '12 Months of Expense')], default=0),
        ),
    ]
