# Generated by Django 2.2.28 on 2023-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0027_auto_20221209_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='auto_fill_amount_to_keep_in_bank',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Auto from income'), (2, '1 Month of Expense'), (3, '2 Months of Expense'), (4, '3 Months of Expense'), (5, '6 Months of Expense'), (6, '12 Months of Expense'), (7, 'Last 12 Months of Expense')], default=0),
        ),
    ]
