# Generated by Django 4.2 on 2023-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0030_add_index_on_source_table'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', '-timestamp', '-created_at'], name='income_inco_user_id_53c411_idx'),
        ),
    ]
