# Generated by Django 4.2 on 2023-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0031_add_index_on_income_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalculation',
            name='auto_fill_amount_to_keep_in_bank',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Auto from income'), (2, 'Auto from expense'), (3, '1 Month of Expense'), (4, '2 Months of Expense'), (5, '3 Months of Expense'), (6, '6 Months of Expense'), (7, '12 Months of Expense'), (8, 'Last 12 Months of Expense')], default=0),
        ),
    ]
